name: workspace
publish_to: none
environment:
  sdk: ^3.7.0-266.0.dev
workspace:
  - pkgs/scribe
  - pkgs/material
  - pkgs/painting
  - pkgs/services
  - pkgs/gemma_ffi
dev_dependencies:
  lints: ^5.1.1
