name: scribe
publish_to: none
version: 0.1.0
resolution: workspace

environment:
  sdk: ^3.7.0-266.0.dev

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Workspace dependencies
  material:
  widgets:
  rendering:
  painting:
  services:

  # UI
  simple_icons: ^10.1.3
  skeletonizer: ^1.4.2
  sliver_tools: ^0.2.12
  gap: ^3.0.1
  google_fonts: ^6.2.1

  cached_network_image: ^3.4.1
  flutter_gen: ^5.8.0
  freezed_annotation: ^2.4.4
  intl: ^0.19.0
  json_annotation: ^4.9.0

  # Text
  markdown: ^7.2.2
  flutter_markdown: ^0.7.4+3
  super_editor: ^0.3.0-dev.12
  super_editor_markdown: ^0.1.7

  flutter_inappwebview: ^6.2.0-beta.2

  # Media player
  media_kit: ^1.1.11
  media_kit_libs_video: ^1.0.5
  media_kit_video: ^1.2.5

  collection: ^1.19.0
  uuid: ^4.5.1
  provider: ^6.1.2
  async: ^2.12.0
  html: ^0.15.5
  http: ^1.2.2

  # Native APIs
  path_provider: ^2.1.5
  share_plus: ^10.1.3
  shared_preferences: ^2.3.5
  url_launcher: ^6.3.1
  flutter_local_notifications: ^19.0.0-dev.3
  flutter_native_splash: ^2.4.3


  app_links: ^6.3.3
  win32_registry: ^1.1.5
  window_manager: ^0.4.3

  flutter_svg: ^2.0.17


  dynamic_color:
    git:
      url: git@github.com:hasali19/material-foundation-flutter-packages.git
      path: packages/dynamic_color

  # Database
  google_sign_in: ^6.2.2
  supabase_flutter: ^2.8.2
  brick_supabase: ^1.3.0
  sqflite: ^2.4.1
  brick_sqlite: ^3.2.1
  sqflite_common_ffi: ^2.3.4+4
  sqlite3_flutter_libs: ^0.5.28
  sqflite_common: ^2.5.4+6
  brick_offline_first_with_supabase: ^1.3.0
  follow_the_leader: ^0.0.4+8
  path_parsing: ^1.1.0
  slang: ^4.4.1
  slang_flutter: ^4.4.0
  super_editor_quill: ^0.1.0-dev.9
  file_picker: ^8.1.7
  archive: ^4.0.2
  path: ^1.9.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.14
  brick_offline_first_with_supabase_build: ^1.1.0
  flutter_gen_runner: ^5.8.0
  freezed: ^2.5.7
  json_serializable: ^6.9.0
  msix: ^3.16.8
  vector_graphics_compiler: ^1.1.16
  slang_build_runner: ^4.4.0

flutter:
  uses-material-design: true
  # generate: true
  assets:
    - assets/images/

flutter_gen:
  output: lib/gen/
  integrations:
    flutter_svg: true
    rive: false
    flare_flutter: false
    lottie: false
